# DATABASE
SQLAlCHEMY_DATABASE_URL = "sqlite+aiosqlite:///data/database.sql"
SQLALCHEMY_TEST_DATABASE_URL = "sqlite+aiosqlite:///:memory:"

# COMMENTS PROPERTIES
MAX_USERNAME_LENGTH = 50
MIN_USERNAME_LENGTH = 2
MAX_COMMENT_LENGTH = 1000
MIN_COMMENT_LENGTH = 2

# TIMEZONE
TIMEZONE = 'Europe/Moscow'
